name: publish

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./distroless

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: login ghcr.io
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: setup
        run: |
          bazel build --host_force_python=PY2 //package_manager:dpkg_parser.par
          sed -i 's/^{/{"experimental": "enabled",/g' ~/.docker/config.json

      - name: build //base:*
        env:
          HUB: ${{ github.ref == 'refs/heads/main' && 'ghcr.io' || 'localhost:5000' }}/${{ github.repository }}
          LANG: base
          USERS: root nonroot
          TOPICS: base debug static
          ARCHS: amd64 arm64
        run: |
          ../hack/bazel_run.sh
          PUSH=1 MANIFEST=1 ../hack/docker_tag_or_push.sh

      - name: build //cc:*
        env:
          HUB: ${{ github.ref == 'refs/heads/main' && 'ghcr.io' || 'localhost:5000' }}/${{ github.repository }}
          LANG: cc
          USERS: root nonroot
          TOPICS: cc debug
          ARCHS: amd64 arm64
        run: |
          ../hack/bazel_run.sh
          PUSH=1 MANIFEST=1 ../hack/docker_tag_or_push.sh
